"""Core data models and enums for RecoverPay AI.

Defines Pydantic schemas for payment records, recovery actions, failure reasons,
and structured exchange between AI and deterministic layers.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator, model_validator


class PaymentStatus(str, Enum):
    """Lifecycle status of a payment transaction."""
    FAILED = "FAILED"
    AT_RISK = "AT_RISK"
    PROCESSING = "PROCESSING"
    RECOVERED = "RECOVERED"
    EXPIRED = "EXPIRED"
    ABANDONED = "ABANDONED"


class FailureReason(str, Enum):
    """Categorized Razorpay failure codes and root causes."""
    BANK_SERVER_DOWN = "BANK_SERVER_DOWN"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS"
    PAYMENT_LIMIT_EXCEEDED = "PAYMENT_LIMIT_EXCEEDED"
    CARD_EXPIRED = "CARD_EXPIRED"
    INVALID_CARD_DETAILS = "INVALID_CARD_DETAILS"
    SUSPECTED_FRAUD = "SUSPECTED_FRAUD"


class RecoveryAction(str, Enum):
    """Allowed recovery strategies mandated by system design."""
    RETRY = "RETRY"
    PAYMENT_LINK = "PAYMENT_LINK"
    REMINDER = "REMINDER"
    INCENTIVE = "INCENTIVE"
    ESCALATE = "ESCALATE"
    STOP = "STOP"


class ProductCategory(str, Enum):
    """Product/service category for risk and margin context."""
    SAAS = "SAAS"
    ECOMMERCE = "ECOMMERCE"
    B2B_SERVICES = "B2B_SERVICES"
    EDTECH = "EDTECH"
    HEALTHCARE = "HEALTHCARE"


class PaymentRecord(BaseModel):
    """Single payment transaction record with customer context.
    
    Guarantees internal consistency between transaction amounts,
    customer payment histories, and failure metadata.
    """
    payment_id: str = Field(
        ...,
        description="Unique Razorpay-style payment identifier (e.g. pay_synth_12345)",
    )
    customer_id: str = Field(
        ...,
        description="Customer identifier (e.g. cust_synth_12345)",
    )
    customer_name: str = Field(
        ...,
        description="Customer full name for notifications and display",
    )
    customer_email: str = Field(
        ...,
        description="Customer email address",
    )
    customer_phone: Optional[str] = Field(
        default=None,
        description="Customer phone number for SMS/WhatsApp/link delivery",
    )
    order_id: str = Field(
        ...,
        description="Unique order identifier (e.g. order_synth_12345)",
    )
    amount: float = Field(
        ...,
        gt=0,
        description="Transaction amount in positive decimal INR",
    )
    currency: str = Field(
        default="INR",
        description="Three-letter ISO currency code, defaulting to INR",
    )
    payment_status: PaymentStatus = Field(
        default=PaymentStatus.FAILED,
        description="Current state of payment record",
    )
    failure_reason: FailureReason = Field(
        ...,
        description="Standardized error category for the failed transaction",
    )
    error_description: Optional[str] = Field(
        default=None,
        description="Raw error message as returned by gateway or issuing bank",
    )
    retry_count: int = Field(
        default=0,
        ge=0,
        description="Number of automated or manual recovery attempts already made",
    )
    customer_previous_payments: int = Field(
        default=0,
        ge=0,
        description="Count of historical successful payments by this customer",
    )
    customer_previous_failures: int = Field(
        default=0,
        ge=0,
        description="Count of historical failed payments by this customer",
    )
    customer_total_spend: float = Field(
        default=0.0,
        ge=0.0,
        description="Cumulative historical revenue generated by this customer in INR",
    )
    days_since_last_success: Optional[int] = Field(
        default=None,
        ge=0,
        description="Days elapsed since the customer's last successful transaction",
    )
    product_category: ProductCategory = Field(
        ...,
        description="Product vertical to guide incentive margins and outreach tone",
    )
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 creation timestamp",
    )

    @field_validator("currency")
    @classmethod
    def validate_currency(cls, v: str) -> str:
        if v.upper() != "INR":
            raise ValueError(f"Only INR currency is currently supported in this MVP, got {v}")
        return v.upper()

    @model_validator(mode="after")
    def validate_customer_history_consistency(self) -> "PaymentRecord":
        """Enforces logical coherence between payments, spend, and recency."""
        # If customer has never paid before, total spend must be 0 and days_since must be None
        if self.customer_previous_payments == 0:
            if self.customer_total_spend > 0.0:
                raise ValueError(
                    f"Inconsistent customer history: customer_previous_payments is 0, "
                    f"but customer_total_spend is {self.customer_total_spend}"
                )
            if self.days_since_last_success is not None:
                raise ValueError(
                    f"Inconsistent customer history: customer_previous_payments is 0, "
                    f"but days_since_last_success is {self.days_since_last_success}"
                )
        else:
            # If customer has previous payments, total spend must be positive
            if self.customer_total_spend <= 0.0:
                raise ValueError(
                    f"Inconsistent customer history: customer_previous_payments is {self.customer_previous_payments}, "
                    f"but customer_total_spend is {self.customer_total_spend}"
                )
            if self.days_since_last_success is None:
                raise ValueError(
                    f"Inconsistent customer history: customer_previous_payments is {self.customer_previous_payments}, "
                    "but days_since_last_success is None"
                )

        return self


# ---------------------------------------------------------------------------
# Structured Schemas for Subsequent Pipeline Steps (AI, Policy, Audit)
# ---------------------------------------------------------------------------

class RecoveryRecommendation(BaseModel):
    """Proposal emitted by the AI Agent for merchant/policy review."""
    action: RecoveryAction = Field(
        ...,
        description="Recommended action: RETRY, PAYMENT_LINK, REMINDER, INCENTIVE, ESCALATE, STOP",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Model confidence score between 0.0 and 1.0",
    )
    discount_pct: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Suggested percentage discount if action is INCENTIVE",
    )
    reasoning: str = Field(
        ...,
        description="Clear, explainable reasoning describing why this recovery path was selected",
    )
    customer_message: Optional[str] = Field(
        default=None,
        description="Tailored notification copy drafted for the customer",
    )


class AIRecommendation(BaseModel):
    """Structured recommendation produced by the AI Recovery Agent (Gemini or Fallback)."""
    action: RecoveryAction = Field(
        ...,
        description="Recommended recovery action: RETRY, PAYMENT_LINK, REMINDER, INCENTIVE, ESCALATE, STOP",
    )
    confidence: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0.0 and 1.0 reflecting strength of evidence",
    )
    reason: str = Field(
        ...,
        description="Concise, human-readable rationale grounded in actual transaction context",
    )
    expected_recovery: float = Field(
        ...,
        ge=0.0,
        description="Estimated potential recovered revenue in INR (cannot be negative)",
    )
    risk_level: str = Field(
        default="LOW",
        description="Risk classification: LOW, MEDIUM, HIGH, or CRITICAL",
    )
    proposed_discount_pct: float = Field(
        default=0.0,
        ge=0.0,
        le=100.0,
        description="Proposed discount percentage when action is INCENTIVE (cannot be negative)",
    )
    requires_approval_recommendation: bool = Field(
        default=False,
        description="Advisory flag indicating whether this recommendation should require merchant approval",
    )
    agent_mode: str = Field(
        default="fallback",
        description="Generation source: 'gemini' or 'fallback'",
    )
    model_name: Optional[str] = Field(
        default=None,
        description="Model name if generated by LLM (e.g. gemini-2.5-flash)",
    )



class PolicyDecisionType(str, Enum):
    """Discrete decision outcome from deterministic policy engine."""
    ALLOWED = "ALLOWED"
    REQUIRES_APPROVAL = "REQUIRES_APPROVAL"
    BLOCKED = "BLOCKED"


class PolicyResult(BaseModel):
    """Deterministic policy evaluation result for a recovery action."""
    decision: PolicyDecisionType = Field(
        ...,
        description="ALLOWED, REQUIRES_APPROVAL, or BLOCKED",
    )
    allowed: bool = Field(
        ...,
        description="True if action can proceed (either immediately or after approval)",
    )
    requires_approval: bool = Field(
        ...,
        description="True if human-in-the-loop merchant approval is strictly required",
    )
    reason: str = Field(
        ...,
        description="Human-readable explanation of why the action was allowed, blocked, or flagged",
    )
    effective_discount: float = Field(
        default=0.0,
        ge=0.0,
        description="Deterministically calculated discount in INR",
    )
    max_allowed_discount: float = Field(
        default=0.0,
        ge=0.0,
        description="Maximum permissible discount in INR under policy caps",
    )
    policy_codes: List[str] = Field(
        default_factory=list,
        description="Standard policy audit codes applied during evaluation",
    )
    payment_id: Optional[str] = Field(
        default=None,
        description="Target payment identifier",
    )
    action: Optional[RecoveryAction] = Field(
        default=None,
        description="The action being evaluated",
    )
    final_payable_amount: Optional[float] = Field(
        default=None,
        description="Exact rupee amount to be charged after discount is deducted",
    )


class PolicyDecision(BaseModel):
    """Deterministic validation result produced by the Policy Engine."""
    status: str = Field(
        ...,
        description="AUTO_APPROVED, REQUIRES_APPROVAL, or BLOCKED",
    )
    approved_action: Optional[RecoveryAction] = Field(
        default=None,
        description="Final action allowed by policy (may override AI if blocked/escalated)",
    )
    approved_discount_pct: float = Field(
        default=0.0,
        ge=0.0,
        description="Clamped incentive percentage strictly conforming to policy caps",
    )
    final_payable_amount: float = Field(
        ...,
        ge=0.0,
        description="Exact rupee amount payable after any approved incentive",
    )
    violations: List[str] = Field(
        default_factory=list,
        description="List of policy rule violations detected, if any",
    )
    requires_merchant_approval: bool = Field(
        default=False,
        description="True if human-in-the-loop merchant approval is strictly required",
    )
    explanation: str = Field(
        default="",
        description="Summary of policy rules applied and any safety overrides",
    )



class RazorpayExecutionResult(BaseModel):
    """Result of executing an approved recovery action via Razorpay test mode or mock sandbox."""
    success: bool = Field(
        ...,
        description="True if action successfully executed without errors",
    )
    action: RecoveryAction = Field(
        ...,
        description="Action that was executed",
    )
    recovery_id: str = Field(
        ...,
        description="Unique recovery attempt ID (e.g. rec_attempt_12345)",
    )
    razorpay_id: Optional[str] = Field(
        default=None,
        description="Razorpay entity ID (order_..., plink_..., or mock_...)",
    )
    status: str = Field(
        ...,
        description="Execution status code: CREATED, PAYMENT_LINK_CREATED, ORDER_CREATED, BLOCKED, APPROVAL_REQUIRED, SIMULATED, FAILED",
    )
    amount: float = Field(
        ...,
        ge=0.0,
        description="Final payable amount charged / linked in INR",
    )
    message: str = Field(
        ...,
        description="Human-readable result summary or error description",
    )
    simulated: bool = Field(
        default=False,
        description="True if generated by mock sandbox provider",
    )
    error_code: Optional[str] = Field(
        default=None,
        description="Error classification code if execution failed or was blocked",
    )
    short_url: Optional[str] = Field(
        default=None,
        description="Hosted checkout short URL if action created a payment link",
    )


class ApprovalStatus(str, Enum):
    """Status of a merchant review request."""
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ApprovalRequest(BaseModel):
    """Record representing a high-value or policy-flagged action awaiting merchant sign-off."""
    approval_id: str = Field(..., description="Unique approval request ID (e.g. app_req_12345)")
    payment_id: str = Field(..., description="Payment ID under review")
    customer_id: str = Field(..., description="Customer ID")
    amount: float = Field(..., ge=0.0, description="Transaction amount in INR")
    requested_action: RecoveryAction = Field(..., description="Action requested by AI")
    ai_reason: str = Field(..., description="AI diagnosis and recovery rationale")
    ai_confidence: float = Field(..., ge=0.0, le=1.0, description="AI confidence score")
    policy_reason: str = Field(..., description="Why policy engine required approval")
    status: ApprovalStatus = Field(default=ApprovalStatus.PENDING, description="PENDING, APPROVED, or REJECTED")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 creation timestamp",
    )
    reviewed_at: Optional[str] = Field(default=None, description="ISO 8601 review timestamp")
    reviewer: Optional[str] = Field(default=None, description="Identifier or name of the merchant reviewer")
    notes: Optional[str] = Field(default=None, description="Optional merchant review comments")


class AuditLogEntry(BaseModel):
    """Immutable audit trail record for compliance and inspection."""
    event_id: str = Field(..., description="Unique event identifier")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="ISO 8601 event timestamp",
    )
    payment_id: str = Field(..., description="Target payment ID")
    action: Optional[str] = Field(default=None, description="Recovery action involved")
    event_type: str = Field(..., description="Event classification (PAYMENT_DETECTED, AI_ANALYZED, etc.)")
    status: str = Field(default="INFO", description="Event status: SUCCESS, FAILED, BLOCKED, etc.")
    message: str = Field(default="", description="Descriptive event message")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Structured event payload")
    recovery_id: Optional[str] = Field(default=None, description="Razorpay recovery ID if available")

    # Backward compatibility property/alias
    @property
    def log_id(self) -> str:
        return self.event_id


class BatchMetrics(BaseModel):
    """Batch recovery financial impact metrics across dataset."""
    total_records: int = Field(default=0, ge=0)
    total_failed_volume: float = Field(default=0.0, ge=0.0)
    total_at_risk_volume: float = Field(default=0.0, ge=0.0)
    total_recovery_opportunities: int = Field(default=0, ge=0)
    actions_executed: int = Field(default=0, ge=0, description="Total recovery actions executed (links created, orders dispatched)")
    successful_recoveries: int = Field(default=0, ge=0, description="Total confirmed (or simulated) recovered payments")
    failed_recoveries: int = Field(default=0, ge=0)
    blocked_actions: int = Field(default=0, ge=0)
    escalations: int = Field(default=0, ge=0)
    approvals_requested: int = Field(default=0, ge=0)
    approvals_granted: int = Field(default=0, ge=0)
    approvals_rejected: int = Field(default=0, ge=0)
    total_recovered_revenue: float = Field(default=0.0, ge=0.0)
    recovery_rate: float = Field(default=0.0, ge=0.0, le=100.0)
    average_recovered_amount: float = Field(default=0.0, ge=0.0)
    incentive_amount_given: float = Field(default=0.0, ge=0.0)
    net_recovered_revenue: float = Field(default=0.0)
    roi: float = Field(default=0.0)
    is_simulated: bool = Field(default=True)

